### ISSUE TITLE
browser crashes while loading some websites into portal

### ISSUE THREAD

**Issue by cydefenser** [WICG/portals#176] opened 2020-02-14 20:14 UTC
i don't know the root cause.. but portal element doesn't behave same for every website.. browser gets crashed while loading some specific websites for example https://twitter.com

to reproduce visit: https://uskay-portals-demo.glitch.me
enter https://twitter.com and browser will crash

one more website for you https://dev.united.com

Please let me know the reason, why its happening. and if there's any work around.

**Comment by kjmcnee** [comment] 2020-02-19 21:03
This sounds like https://crbug.com/1038256 which is a crash when logging that we did not load due to X-Frame-Options. Please check which version of chrome you're experiencing the crash on. This issue should be fixed in chrome version 81.0.4033.2 and later.

**Comment by cydefenser** [comment] 2020-02-19 21:14
i am using chrome Version 80.0.3987.116 (Official Build) (64-bit) for mac

**Comment by kjmcnee** [comment] 2020-02-19 22:39
I can confirm that performing the above steps on version 80.0.3987.116 causes the same X-Frame-Options related crash.

**Comment by kjmcnee** [comment] 2020-02-20 15:43
Closing this per my previous comment.

**Closed by kjmcnee** 2020-02-20 15:43 UTC
