### ISSUE TITLE
portalactivate custom/default action for successor page

### ISSUE THREAD

**Issue by rinodrummer** [WICG/portals#163] opened 2019-12-05 06:30 UTC
Using portals with external website (for test purpose) I got stack in the successor page because (obviously) there was no `portalactivate` event listeners.

May we be able to make a custom `portalactivate` handler that can control how we want to interact with the successor page? Or will a default action for this event be supplied?

If not, can an HTML property be specified to make sure that the user can navigate back to the predecessor page using the history controls?

**Comment by jeremyroman** [comment] 2019-12-05 15:18
It is intended that you be able to navigate back; that you couldn't was a bug in the Chromium implementation.

Though the spec wording of this hasn't landed yet, the latest Chrome Canary should have better behavior in this regard. @kjmcnee anything else to add here?

**Comment by rinodrummer** [comment] 2019-12-05 16:43
Just to add details, I'm using Google Chrome 78.0.3904.108.

**Comment by kjmcnee** [comment] 2019-12-05 16:58
Right, the history controls not working across a portal activation was an issue fixed in chromium version 80.0.3980.0. The browser will treat the portal activation like a regular navigation in terms of how it affects session history. So there will be no need to adopt the predecessor just to make session history work.

**Comment by juliadou** [comment] 2019-12-09 17:13
I just downloaded chrome unstable version 80.0.3983.2 on linux. The page crashes whenever portal is appended to the DOM.

**Comment by jeremyroman** [comment] 2019-12-09 18:10
Please report Chromium implementation bugs (with a reproduction case, if possible) on crbug.com/new. Thanks. :)

**Comment by domenic** [comment] 2020-05-08 21:15
Since this seems to mostly be about Chromium issues, I'll close it, since those are tracked on crbug.com. If I misunderstood, let me know and we can reopen.

**Closed by domenic** 2020-05-08 21:15 UTC
