### ISSUE TITLE
Is there a way to know whether the portal content is loaded

### ISSUE THREAD

**Issue by juliadou** [WICG/portals#165] opened 2019-12-09 16:41 UTC
After I create a portal with Site B in Site A, i would like to detect whether the portal content is loaded. Is there a way to achieve this?

I initially thought it could be achieved using messaging, but it seems only Site A can message the portal (Site B) and not vice versa.

**Comment by lucasgadani** [comment] 2019-12-09 16:44
Both sites should be able to postMessage each other. From the portal host, you can use the <portal>.postMessage() API. The other way around you need to use the portalHost interface, window.portalHost.postMessage().

The other option is to listen to the load event on the <portal> element. This can be done by listening to the <portal>.onload event.

**Comment by juliadou** [comment] 2019-12-09 17:30
Thank you! I tried portal.onload and it works great.

Regarding window.portalHost.postMessage, If I add it to Site B so Site B can post message to Site A, how can Site A receive the message? I tried to add `window.addEventListener('message', callback)` to Site A and it does not seem to work.

**Comment by a4sriniv** [comment] 2019-12-09 18:06
The message gets dispatched on the portal element, so you need to use `portal.addEventListener('message', callback')`.

**Comment by domenic** [comment] 2020-05-08 21:17
This seems like a duplicate of #26, so I'll consolidate there. However it sounds like from @lucasgadani's comments Chromium implements the load event, so that's good input for #26 :).

**Closed by domenic** 2020-05-08 21:17 UTC
